{% set name = "debugpy" %}
{% set version = "1.8.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 31e69a1feb1cf6b51efbed3f6c9b0ef03bc46ff050679c4be7ea6d2e23540870

  - url: https://github.com/microsoft/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: cce9b8aeed25f8ba33df464283112a87a7881e5d3b5dc3c9f30dc9852ec123db
    folder: gh_src

build:
  number: 0
  entry_points:
    - debugpy = debugpy.server.cli:main
    - debugpy-adapter = debugpy.adapter.__main__:main

requirements:
  build:
    - python
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

{% set SKIP_TEST_FILES = [
    "gh_src/tests/debugpy/test_flask.py",
    "gh_src/tests/debugpy/test_django.py",
    "gh_src/tests/debugpy/test_gevent.py",
    "gh_src/tests/debugpy/test_numpy.py"
] %}

{% set SKIP_TEST_COMMON = [
    "attach_pid",
    "django",
    "flask",
    "gevent",
    "numpy"
] %}

# FileNotFoundError: [Errno 2] No such file or directory:
# 'C:\\miniconda3\\conda-bld\\debugpy_1757036819533\\test_tmp\\gh_src\\tests\\test_data\\bp\\ನನ್ನ_ಸ್ಕ್ರಿಪ್ಟ್.py'
{% set SKIP_TEST_WIN = [
    "test_path_with_unicode"
] %}

{% set SKIP_TEST_LIST = [] %}
{% set SKIP_TEST_LIST = SKIP_TEST_LIST + SKIP_TEST_COMMON %}
{% set SKIP_TEST_LIST = SKIP_TEST_LIST + SKIP_TEST_WIN %}  # [win]

test:
  source_files:
    - gh_src/tests
  imports:
    - debugpy
    - debugpy.adapter
    - debugpy.common
    - debugpy.launcher
    - debugpy.server
  requires:
    - pip
    - pytest
    - pytest-xdist
    - pytest-timeout
    - psutil
    - requests
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - python -m pytest -ra -vvv -n auto --dist=loadfile --timeout=60 --timeout-method=thread --durations=25 -o pythonpath=gh_src gh_src/tests/debugpy {% for file in SKIP_TEST_FILES %} --ignore={{ file }}{% endfor %} -k "not ({{ SKIP_TEST_LIST | join(' or ') }})"

about:
  home: https://github.com/Microsoft/debugpy
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - ThirdPartyNotices.txt
  summary: An implementation of the Debug Adapter Protocol for Python
  dev_url: https://github.com/microsoft/debugpy
  doc_url: https://github.com/microsoft/debugpy
  description: An implementation of the Debug Adapter Protocol for Python

extra:
  recipe-maintainers:
    - jtilly
    - xhochy
