{% set name = "debugpy" %}
{% set version = "1.8.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 31e69a1feb1cf6b51efbed3f6c9b0ef03bc46ff050679c4be7ea6d2e23540870

build:
  number: 0
  entry_points:
    - debugpy = debugpy.server.cli:main
  ignore_run_exports:
    - libcxx  # [osx]

requirements:
  build:
    - python
    - {{ compiler('c') }}           # [unix]
    - {{ compiler('cxx') }}         # [unix]
    - pkg-config                    # [linux]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - debugpy
    - debugpy.adapter
    - debugpy.common
    - debugpy.launcher
    - debugpy.server

about:
  home: https://github.com/Microsoft/debugpy
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - ThirdPartyNotices.txt
  summary: An implementation of the Debug Adapter Protocol for Python
  dev_url: https://github.com/microsoft/debugpy
  doc_url: https://github.com/microsoft/debugpy
  description: An implementation of the Debug Adapter Protocol for Python

extra:
  recipe-maintainers:
    - jtilly
    - xhochy
